# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/FPGA/Projects/RISCV/tinyriscv/.Xil/Vivado-9572-lizi2033/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tfgg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/defines.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/clint.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/csr_reg.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/ctrl.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/div.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/ex.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/utils/full_handshake_rx.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/utils/full_handshake_tx.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/utils/gen_dff.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/gpio.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/id.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/id_ex.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/if_id.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/debug/jtag_dm.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/debug/jtag_driver.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/debug/jtag_top.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/pc_reg.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/ram.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/regs.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/rib.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/rom.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/spi.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/timer.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/core/tinyriscv.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/perips/uart.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/debug/uart_debug.v
      D:/FPGA/Projects/RISCV/tinyriscv/tinyriscv.ip_user_files/rtl/soc/tinyriscv_soc_top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top tinyriscv_soc_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/FPGA/Projects/RISCV/tinyriscv/.Xil/Vivado-9572-lizi2033/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
